### PR TITLE
Removed setting cwd

### PR DESCRIPTION
**Pull request by mountainash**
With `cwd` being set I was constantly getting the following "RuntimeError: Environment went away" error.
```
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lektor/admin/utils.py", line 18, in generate
    for event in chain(f(*args, **kwargs), (None,)):
  File "/usr/local/lib/python3.7/site-packages/lektor/admin/modules/api.py", line 315, in generator
    for event in event_iter:
  File "/usr/local/lib/python3.7/site-packages/lektor_git_src_publisher.py", line 72, in publish
    for line in self._git(["fetch", "--progress"]).output:
  File "/usr/local/lib/python3.7/site-packages/lektor_git_src_publisher.py", line 17, in _git
    root_path = self._plugin.env.root_path
  File "/usr/local/lib/python3.7/site-packages/lektor/pluginsystem.py", line 40, in env
    raise RuntimeError('Environment went away')
RuntimeError: Environment went away
```

### CODE REVIEW

**Comment by evilham** [comment]
Haha, congratulations on securing the #1 :-).

I'll have to test this before merging (hopefully tomorrow), but I *think* this might be breaking setups where `.lektorproject` is not in the cwd, aka, when executed with `lektor --project PATH`.

Worst case it does break and we'll have to add some logic around that, thank you for reporting though!

**Comment by evilham** [comment]
\o sorry for taking *so long* with this. Indeed there was an issue with setups where `lektor --project PATH` is necessary.
I believe the committed code fixes this while not breaking such setups.

Thank you!

**Comment by mountainash** [comment]
This is still an issue. Could it also be that the `{sitename}.lektorproject` file isn't at the root of the git project (it's 2 levels deeper).

Here's the latest logs from using `0.2.1` of the plugin:
```log
lektor_1  |   Tree: /srv/lektor/src
lektor_1  |   Output path: /root/.cache/lektor/builds/6ee38462ce1b578e8e036dfceba4adfd
lektor_1  | Finished prune in 0.15 sec
lektor_1  | /usr/local/lib/python3.8/site-packages/werkzeug/serving.py:320: ResourceWarning: unclosed file <_io.BufferedReader name='/root/.cache/lektor/builds/6ee38462ce1b578e8e036dfceba4adfd/fonts/PatronWEB-Italic.woff'>
lektor_1  |   application_iter.close()
lektor_1  | ResourceWarning: Enable tracemalloc to get the object allocation traceback
lektor_1  | /usr/local/lib/python3.8/site-packages/werkzeug/serving.py:320: ResourceWarning: unclosed file <_io.BufferedReader name='/root/.cache/lektor/builds/6ee38462ce1b578e8e036dfceba4adfd/fonts/PatronWEB-Regular.woff'>
lektor_1  |   application_iter.close()
lektor_1  | ResourceWarning: Enable tracemalloc to get the object allocation traceback
lektor_1  | /usr/local/lib/python3.8/site-packages/werkzeug/serving.py:320: ResourceWarning: unclosed file <_io.BufferedReader name='/root/.cache/lektor/builds/6ee38462ce1b578e8e036dfceba4adfd/static/img/side_image_1.jpg'>
lektor_1  |   application_iter.close()
lektor_1  | ResourceWarning: Enable tracemalloc to get the object allocation traceback
lektor_1  | Debugging middleware caught exception in streamed response at a point where response headers were already sent.
lektor_1  | Traceback (most recent call last):
lektor_1  |   File "/usr/local/lib/python3.8/site-packages/lektor/admin/utils.py", line 18, in generate
lektor_1  |     for event in chain(f(*args, **kwargs), (None,)):
lektor_1  |   File "/usr/local/lib/python3.8/site-packages/lektor/admin/modules/api.py", line 315, in generator
lektor_1  |     for event in event_iter:
lektor_1  |   File "/usr/local/lib/python3.8/site-packages/lektor_git_src_publisher.py", line 123, in publish
lektor_1  |     yield self._git_output(["add", "."])
lektor_1  |   File "/usr/local/lib/python3.8/site-packages/lektor_git_src_publisher.py", line 34, in _git_output
lektor_1  |     return self._git(args, **kwargs).stdout
lektor_1  |   File "/usr/local/lib/python3.8/site-packages/lektor_git_src_publisher.py", line 18, in _git
lektor_1  |     root_path = self._plugin.env.root_path
lektor_1  |   File "/usr/local/lib/python3.8/site-packages/lektor/pluginsystem.py", line 40, in env
lektor_1  |     raise RuntimeError('Environment went away')
lektor_1  | RuntimeError: Environment went away
```

Sidenote: the `io.BufferedReader` errors only show when using this update - reverting to my previous patch doesn't show these issues.

**Comment by mountainash** [comment]
I've [created a fork](https://github.com/mountainash/lektor-git-src-publisher/tree/v0.2.1/fix-env-went-away) doing the [same git args changes](https://github.com/CamilionEU/lektor-git-src-publisher/compare/main...mountainash:v0.2.1/fix-env-went-away) as I did with the first version of this project, and it works perfectly again.

**Pull request closed without merging**
